### ISSUE TITLE
Reordenar tarefas

### ISSUE THREAD

**Issue by paulojunior-ufla** [dcc-ufla/tarefas#1]
Permitir que a lista de tarefas seja reordenada pelo usuário. O **Ionic** já possui um componente preparado para esse tipo de funcionalidade, denominado `ion-reorder`. Veja mais sobre ele [aqui](https://ionicframework.com/docs/api/reorder).

**Comment by paulorsv01** [comment]
Olá @paulojunior-ufla, eu gostaria de trabalhar nesta _issue_, caso não tenha outra pessoa trabalhando nela.

**Comment by paulojunior-ufla** [comment]
Olá, @paulorsv01. Obrigado pelo interesse. Aguardo seu PR...

**Comment by paulorsv01** [comment]
Boa noite, @paulojunior-ufla!
Consegui implementar uma versão inicial, porém fiquei com algumas dúvidas com relação ao comportamento e aos ícones que serão utilizados. 
- Sobre o comportamento, pensei em deixar a feature por trás de um toggle, estilo como é feito na documentação do componente. O que acha? 
	- E caso a abordagem escolhida seja essa do toggle: pensando no app de tarefas, onde poderia ficar o ícone/texto? Penso que no menu de tarefas não seria um bom lugar, então pensei em talvez colocar no header (no lugar circulado de verde), porém queria ver a sua opinião antes.

    ![image](https://user-images.githubusercontent.com/16693325/186995313-f1b77dc1-648f-49f4-965e-0b4676adfc44.png)

- Sobre os ícones, encontrei esse pack: https://ionic.io/ionicons, que me parece ser o que é usado no projeto. Nos ícones do pack, o `reorder-three-outline` me chamou a atenção para ser o ícone do reorder, e caso o comportamento seja o de ter um botão para toggle, o ícone `swap-vertical-outline` me chamou a atenção. O que acha?

    | swap-vertical-outline | reorder-three-outline |
    | - | - |
    | ![image](https://user-images.githubusercontent.com/16693325/186995811-939dedac-b999-4e0a-b4ea-203b5a3a0a00.png) | ![image](https://user-images.githubusercontent.com/16693325/186995816-b13f9c79-8dc0-40b3-941d-2b9e686a7560.png) |

**Comment by paulojunior-ufla** [comment]
Olá, @paulorsv01. Gostei das escolhas que você fez. Apenas o posicionamento do ícone de _toggle_ me deixou na dúvida. Mas, após ver a aplicação em funcionamento, pode ser que a dúvida se dissipe. Portanto, pode seguir com suas escolhas para o PR. Obrigado mais uma vez por sua colaboração!
